### ISSUE TITLE
Fix Linux compillation

### ISSUE THREAD

**Issue by trufanov-nok** [lgolouz/ZXTapeReviver#40]
Hi,
If one will try to build the project under some Linux machine the build process fails.
Qt applications could be easily build on Linux from command line:
```
mkdir build
cd build
qmake ..
make
```
Build process stops with a following error:
```
g++ -c -pipe -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DAVAILABLE_TRANSLATIONS=\"English:en_US;Russian:ru_RU\" -DCOUNTRY_CODES=en_US,ru_RU -DTRANSLATION_IDS_HEADER=\"/tmp/ZXTapeReviver/generated/translations_generated.h\" -DTRANSLATION_IDS_CODE=\"/tmp/ZXTapeReviver/generated/translations_generated.cpp\" -DZXTAPEREVIVER_VERSION=\"ZXTAPEREVIVER_v0.5.1\" -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../ZXTapeReviver -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o ../sources/main.cpp
g++: fatal error: no input files
compilation terminated.
/bin/sh: 1: Russian:ru_RU": not found
make: *** [Makefile:677: main.o] Error 127
```

That's because of `-DAVAILABLE_TRANSLATIONS=\"English:en_US;Russian:ru_RU\"` in executed command. The right command line would contain `-DAVAILABLE_TRANSLATIONS="\"English:en_US;Russian:ru_RU\""`

I suggest to replace the line 
`DEFINES += AVAILABLE_TRANSLATIONS=\\\"$${DEFINED_TRANSLATIONS}\\\" \`
in `ZXTapeReviver.pro` with the
`DEFINES += AVAILABLE_TRANSLATIONS=\"\\\"$${DEFINED_TRANSLATIONS}\\\"\" \`

In this case the project compiles fine, the app may be launched and Russian language is selectable from menu.
Could you please check if it still works on a Win machine and consider to adjust this line.

**Comment by lgolouz** [comment]
@trufanov-nok , looks like fix you proposed works great on Windows. Please, make pull request to integrate it.
