### ISSUE TITLE
Uninitialized variable: tdx error

### ISSUE THREAD

**Issue by ZanyXDev** [lgolouz/ZXTapeReviver#42]
https://github.com/lgolouz/ZXTapeReviver/blob/f94cbe69a6bdd4ef43ffea5baaf2f9691acf803f/sources/controls/waveformcontrol.cpp#L70

**Comment by lgolouz** [comment]
There is no need to initialize tdx, as it will be used only in case of null dx and its value will be dropped. This is temporary variable to fake store the value in case of no return value needed.
