### ISSUE TITLE
Possible extract to inline function ?

### ISSUE THREAD

**Issue by ZanyXDev** [lgolouz/ZXTapeReviver#43]
https://github.com/lgolouz/ZXTapeReviver/blob/f94cbe69a6bdd4ef43ffea5baaf2f9691acf803f/sources/core/waveformparser.cpp#L159

https://github.com/lgolouz/ZXTapeReviver/blob/f94cbe69a6bdd4ef43ffea5baaf2f9691acf803f/sources/core/waveformparser.cpp#L183
```              
  if (bitIndex < 0) {
                        parsedWaveform[it->end] ^= byteBound;
                        bitIndex = 7;
                        data.append(bit);
                        waveformData.append(*it);
                        parity ^= bit;
                        bit ^= bit;
                    }
```

**Comment by lgolouz** [comment]
@ZanyXDev not relevant due to new code changes
